sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: T1X3nU4P1JxQ+y/C6BdhZCffec9LBftn/hPwHbdfp7zOOy7YK+PplJ5hrZj2frZ0GQohygOrcDGi294ZRzhLvSC1tNYN5HzlwNYxPtwKPh7j3RRcrOI6y9y5Y7G5U0Nd00EnEM3eNXd/X+5W+JQTHjkfsAT+VicymsgyigDaeM+HXK7l0x7LsSzJiDngumvn9CDezzQQK0tzRlcraCrd/ISheIZoUKad0P6twZF6Q9yb0FzOCaiqjx4XU9J3armAiq1nChIgVw8jpoi2HKcmYbVb5YbYAhf8vHkOvcTfmAvDTID5QFHqSzjEuVm98WoShQdFRgVCiZVGCyrrEK9cPA2DV6rQRGjveSv2vWPkiQOl8OQzGJe82lKEtLpx19unKgv8Ajn2qmKgGOlV0sSQAvOWAckLC1d9LSBPxaoW9Az0jxgRv6P7XiKdP0ZuEh3ZSN60L2TRCoBAMdHNqXCRrKLFjzMWO3+5yRqDWe2or6uiHXVxiasDuSZ5gaV9lC8HILCc1miEp3QKrCIS+MPKpMOX/bE3Ils/UagaZb5z3PlfwKLt4hzf8IyQ09Leu+tJbOea/+/iewxtmo/AuV93+nJTFTkdg3XJOCTgjyewQojA7xmSWmsMb+WJFRC9fgNtSzmj3ObnTDVYxUdIaTMYqb/0wPi07iBckHF7D7X3Ql0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Scouts-of-Stonewall--The-Story-of-the-Great-Valley-Campaign_6094
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy